# .bandit.yml
skips: ["B101", "B104"] # Skip assert_used and hardcoded_bind_all_interfaces

# Customize severity levels
severity: ["HIGH", "MEDIUM"]

# Include specific test IDs
tests:
  [
    "B102",
    "B103",
    "B105",
    "B106",
    "B107",
    "B108",
    "B109",
    "B110",
    "B112",
    "B113",
    "B201",
    "B301",
    "B302",
    "B303",
    "B304",
    "B305",
    "B306",
    "B307",
    "B308",
    "B309",
    "B310",
    "B311",
    "B312",
    "B313",
    "B314",
    "B315",
    "B316",
    "B317",
    "B318",
    "B319",
    "B320",
    "B321",
    "B322",
    "B323",
    "B324",
    "B325",
    "B326",
    "B327",
    "B328",
    "B329",
    "B330",
    "B331",
    "B332",
    "B333",
    "B334",
    "B335",
    "B336",
    "B337",
    "B338",
    "B339",
    "B340",
    "B341",
    "B342",
    "B343",
    "B344",
    "B345",
    "B346",
    "B347",
    "B348",
    "B349",
    "B350",
    "B351",
    "B352",
    "B353",
    "B354",
    "B355",
    "B356",
    "B357",
    "B358",
    "B359",
    "B360",
    "B361",
    "B362",
    "B363",
    "B364",
    "B365",
    "B366",
    "B367",
    "B368",
    "B369",
    "B370",
    "B371",
    "B372",
    "B373",
    "B374",
    "B375",
    "B376",
    "B377",
    "B378",
    "B379",
    "B380",
    "B381",
    "B382",
    "B383",
    "B384",
    "B385",
    "B386",
    "B387",
    "B388",
    "B389",
    "B390",
    "B391",
    "B392",
    "B393",
    "B394",
    "B395",
    "B396",
    "B397",
    "B398",
    "B399",
    "B400",
    "B401",
    "B402",
    "B403",
    "B404",
    "B405",
    "B406",
    "B407",
    "B408",
    "B409",
    "B410",
    "B411",
    "B412",
    "B413",
    "B414",
    "B415",
    "B416",
    "B417",
    "B418",
    "B419",
    "B420",
    "B421",
    "B422",
    "B423",
    "B424",
    "B425",
    "B426",
    "B427",
    "B428",
    "B429",
    "B430",
    "B431",
    "B432",
    "B433",
    "B434",
    "B435",
    "B436",
    "B437",
    "B438",
    "B439",
    "B440",
    "B441",
    "B442",
    "B443",
    "B444",
    "B445",
    "B446",
    "B447",
    "B448",
    "B449",
    "B450",
    "B451",
    "B452",
    "B453",
    "B454",
    "B455",
    "B456",
    "B457",
    "B458",
    "B459",
    "B460",
    "B461",
    "B462",
    "B463",
    "B464",
    "B465",
    "B466",
    "B467",
    "B468",
    "B469",
    "B470",
    "B471",
    "B472",
    "B473",
    "B474",
    "B475",
    "B476",
    "B477",
    "B478",
    "B479",
    "B480",
    "B481",
    "B482",
    "B483",
    "B484",
    "B485",
    "B486",
    "B487",
    "B488",
    "B489",
    "B490",
    "B491",
    "B492",
    "B493",
    "B494",
    "B495",
    "B496",
    "B497",
    "B498",
    "B499",
    "B500",
    "B501",
    "B502",
    "B503",
    "B504",
    "B505",
    "B506",
    "B507",
    "B508",
    "B509",
    "B510",
    "B511",
    "B512",
    "B513",
    "B514",
    "B515",
    "B516",
    "B517",
    "B518",
    "B519",
    "B520",
    "B521",
    "B522",
    "B523",
    "B524",
    "B525",
    "B526",
    "B527",
    "B528",
    "B529",
    "B530",
    "B531",
    "B532",
    "B533",
    "B534",
    "B535",
    "B536",
    "B537",
    "B538",
    "B539",
    "B540",
    "B541",
    "B542",
    "B543",
    "B544",
    "B545",
    "B546",
    "B547",
    "B548",
    "B549",
    "B550",
    "B551",
    "B552",
    "B553",
    "B554",
    "B555",
    "B556",
    "B557",
    "B558",
    "B559",
    "B560",
    "B561",
    "B562",
    "B563",
    "B564",
    "B565",
    "B566",
    "B567",
    "B568",
    "B569",
    "B570",
    "B571",
    "B572",
    "B573",
    "B574",
    "B575",
    "B576",
    "B577",
    "B578",
    "B579",
    "B580",
    "B581",
    "B582",
    "B583",
    "B584",
    "B585",
    "B586",
    "B587",
    "B588",
    "B589",
    "B590",
    "B591",
    "B592",
    "B593",
    "B594",
    "B595",
    "B596",
    "B597",
    "B598",
    "B599",
    "B601",
    "B602",
    "B603",
    "B604",
    "B605",
    "B606",
    "B607",
    "B608",
    "B609",
    "B610",
    "B611",
    "B612",
    "B613",
    "B614",
    "B615",
    "B616",
    "B617",
    "B618",
    "B619",
    "B620",
    "B621",
    "B622",
    "B623",
    "B624",
    "B625",
    "B626",
    "B627",
    "B628",
    "B629",
    "B630",
    "B631",
    "B632",
    "B633",
    "B634",
    "B635",
    "B636",
    "B637",
    "B638",
    "B639",
    "B640",
    "B641",
    "B642",
    "B643",
    "B644",
    "B645",
    "B646",
    "B647",
    "B648",
    "B649",
    "B650",
    "B651",
    "B652",
    "B653",
    "B654",
    "B655",
    "B656",
    "B657",
    "B658",
    "B659",
    "B660",
    "B661",
    "B662",
    "B663",
    "B664",
    "B665",
    "B666",
    "B667",
    "B668",
    "B669",
    "B670",
    "B671",
    "B672",
    "B673",
    "B674",
    "B675",
    "B676",
    "B677",
    "B678",
    "B679",
    "B680",
    "B681",
    "B682",
    "B683",
    "B684",
    "B685",
    "B686",
    "B687",
    "B688",
    "B689",
    "B690",
    "B691",
    "B692",
    "B693",
    "B694",
    "B695",
    "B696",
    "B697",
    "B698",
    "B699",
  ]
